### ISSUE TITLE
Containers (LXC) support

### ISSUE THREAD

**Issue by yuri-ccp** [AlmaLinux/leapp-data#108]
I'm running some CentOS 7 containers and I was trying to elevate these containers but leapp fails complaining that it doesn´t find grub or grubby or the kernel package but in fact these things doesn´t exist in containers once the aren´t needed and containers don´t requires then to run.

In order to work in containers leapp needs to detect and ignore all hardware and boot part when running in a container.

**Comment by andrewlukoshko** [comment]
Leapp requires grub2 and initramfs to work.
That's why it's impossible to use it inside containers.

**Comment by yuri-ccp** [comment]
Wouldn't it be possible to implement a condition for it to detect the container and ignore grub2 and the initram?

Especially since GRUB2 won't last forever, and the initram has multiple implementations too (just like init was replaced by systemd between CentOS 6 and 7). I know that today for the Almalinux scenario it is quite stable in this regard, but in the future it may change, so adding some checks and exceptions may help with that too.

Anyway, I understand if you don't want to worry about this for now, but it's a shame and a severe limitation for this type of system design to facilitate the change of OS versions if it is restricted to very specific scenarios and forces those who don't follow this scenario to have to not use it. It goes against the idea of ​​the project itself IMO.
