### ISSUE TITLE
Rocky logos package split

### ISSUE THREAD

**Issue by coffmant** [AlmaLinux/leapp-data#2]
The Rocky data needs the same fix that Oracle received in https://github.com/AlmaLinux/leapp-data/commit/fcb09336bb56850f5de32b2f07d4c2881db6cc61

**Comment by andrewlukoshko** [comment]
Added new action https://pes.almalinux.org/view_action/2219
Will sync json with PES soon

**Comment by andrewlukoshko** [comment]
New version of leapp-data-rocky package was released
