### ISSUE TITLE
Newest leapp-data-rocky package not working correctly

### ISSUE THREAD

**Issue by drikqlis** [AlmaLinux/leapp-data#42]
When using newest leapp-data-rocky package to upgrade Centos 7 to Rocky 8 there is an error when running leapp preupgrade:
```
Upgrade has been inhibited due to the following problems:
    1. Inhibitor: Missing/Invalid PES data file (/etc/leapp/files/pes-events.json)
```
If we remove this package and install previous version it works correctly:
```
yum remove leapp-data-rocky
yum install leapp-data-rocky-0.2-4.el7.noarch
```
Looks like others also encountered this issue: https://forums.rockylinux.org/t/inhibitor-missing-invalid-pes-data-file-etc-leapp-files-pes-events-json/13055

**Comment by andrewlukoshko** [comment]
Fixed.
