### ISSUE TITLE
Latest leapp-data-rocky version is not worked in Cent OS 7.9

### ISSUE THREAD

**Issue by pinebana** [AlmaLinux/leapp-data#43]
Hello, I'm working on a migration from CentOS 7.9 to Rocky 8.9 using this projects package.

However, I was able to see that migration was not performed normally in the most recent version. 
The CentOS version information is as follows. I used the CentOS official AMI in AWS Clouds.

```
$ sudo cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)
$ uname -r
3.10.0-1160.108.1.el7.x86_64

$ sudo yum list installed | grep rocky
leapp-data-rocky.noarch               0.2-5.el7                     @elevate
```

During the preupgrade process, the failure is as follows.
> Upgrade has been inhibited due to the following problems:
>  1. Inhibitor: Missing/Invalid PES data file (/etc/leapp/files/pes-events.json)
> Consult the pre-upgrade report for details and possible remediation.

I did the migration back to the version I used before to check the content, and I was able to confirm that it was working properly.

```
$ sudo yum install -y leapp-upgrade leapp-data-rocky-0.2.4.el7
$ sudo yum list installed | grep rocky 
leapp-data-rocky.noarch               0.2-4.el7                     @elevate
```

I would appreciate it if you could check this issue. 
Thank you :)

**Comment by andrewlukoshko** [comment]
Thank you. Broken package was removed from ELevate repos.
We're investigating the issue.
